### ISSUE TITLE
unable to install the font

### ISSUE THREAD

**Issue by pavelapekhtin** [mcarvalho1/Nerd-fonts-Downloader-Script#6]
Tried running on Ubuntu/WSL2, outputs an error after .zip or tarball option:

```
Enter your choice: 27
Choose the extension to install:
[1] - .zip
[2] - .tar.xz
Enter the number of the desired extension: 2
./nf_downloader.sh: line 160: jq: command not found
Choose version to install, enter a specific version using the vX.Y.Z format (latest version: )
```

**Comment by zzaurav** [comment]
@pavelapekhtin `sudo apt install jq` if using Debian/Ubuntu and proceed from there. 

You should now see the (latest version: ) populate with an actual version number and select that number when you proceed!

**Comment by mcarvalho1** [comment]
@pavelapekhtin I've made some improvements to the code and added jq as a dependency, so the latest version will always appear. Thanks for reporting the error.

And many thanks to @realsshrestha for providing a brief solution to the problem.
